[project]
name = "q-receive"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pyyaml>=6.0.2",
    "requests>=2.32.3",
    "selenium>=4.28.1",
]

[dependency-groups]
dev = [
    "pyinstaller>=6.11.1",
]
